name: Cleanup Old Deployments

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types: [completed]
  workflow_dispatch:

permissions:
  deployments: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Delete old github-pages deployments
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyDeactivateDeployments: false
          onlyRemoveDeployments: true